config/routes.rb
Rails.application.routes.draw do
  get 'articles/index'

  get 'users/index'

  get 'products/index'

  get 'page' => 'page#home'
  get 'page/index'
  get 'page/show'
  #get 'welcome/index' --Este se pone por default con el generate controller
  get '/welcome' => 'welcome#index'
  root 'welcome#index' #root nos lleva al home por default
  get '/hello/:name', to: "welcome#hello", as: "hello" #le estamos dando una variable obligatoria a nuestro metodo
  #NOTA: le damos este as para poder referenciarlo desde la app, pues como tiene una variable no se puede normalito!!
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
# == Schema Information
#
# Table name: articles
#
#  id         :integer          not null, primary key
#  name       :string
#  fecha      :date
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Article < ApplicationRecord
end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id          :integer          not null, primary key
#  name        :string
#  description :text
#  price       :decimal(, )
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  user_id     :integer
#  published   :boolean
#  category    :string
#

class Product < ApplicationRecord
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  name       :string
#  correo     :text
#  telefono   :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
  end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
#layout "my_layout"   #le estamos diciendo que use este layout y no el de default
#los Layout deben espesificarse afuera de los metodos
#para usar varios layout en diferentes metodos:
layout "my_layout", only: [:index, :show]

  def home
  end

  def index
    render :index_2 #le estamos diciendo que vaya a la vista del index 2, no a la de index!
  end

  def show
    redirect_to page_path #nos lleva de una al page Home
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index #no es necesario espesificar que vaya a la visto, lo hace el solito
    @name = "Isabel" #ya podemos usar esta variable de instancia en nuestra vista
  end

  def hello
    @name = params[:name] #en este caso como la variable viene en la ruta hay que sacarlas del hash
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/index.html.erb
<h1>Articles#index</h1>
<p>Find me in app/views/articles/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrimeraApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-inverse">
    <div class="container-fluid">
      <div class="navbar-header">
        <a class="navbar-brand" href="#"><span class="glyphicon glyphicon-home" aria-hidden="true"></span></a>
      </div>
      <ul class="nav navbar-nav">
        <li ><a href="/welcome">Home</a></li>
        <li><a href="/page">Page</a></li>
        <li><a href="/products/index">Products</a></li>
      </ul>
    </div>
  </nav>
    <%= yield %>
  </body>
</html>

app/views/layouts/my_layout.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>My Layout</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/page/home.html.erb
<h1>PAGE-HOME</h1>
<%= link_to "Ir-Home", welcome_path %><!-- hacen lo mismo, pero esta usa un helper -->

app/views/page/index.html.erb
<h1>WELCOME</h1>
<p>Yo soy <%=@name%> y esta es mi primera vista en make it real</p>

app/views/page/index_2.html.erb
<h1>Este es el index 2</h1>
<p>Yo soy <%=@name%> y esta es mi primera vista en make it real</p>

app/views/page/show.html.erb
<h1>Mostrar algo</h1>

app/views/products/index.html.erb
<div class= "container">
<h1>Productos</h1>
<table class="table table-striped">
    <thead>
      <tr>
        <th>Nombre</th>
        <th>Descripsion</th>
        <th>Precio</th>
      </tr>
    </thead>
    <% @products.each do |prod| %>
    <tbody>
      <tr>
        <td><%=prod.name%></td>
        <td><%=prod.description%></td>
        <td><%=prod.price%></td>
      </tr>
    </tbody>
    <%end%>
  </table>
</div>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/welcome/hello.html.erb
<h1> Hola <%=@name %> </h1>
<!--<a href="<%= welcome_path %>">Ir al Home</a> para referenciar un path es el prifix_path -->
<%= link_to "Ir-Home", welcome_path %><!-- hacen lo mismo, pero esta usa un helper -->

app/views/welcome/index.html.erb
<h1>WELCOME</h1>
<p>Yo soy <%=@name%> y esta es mi primera vista en make it real</p>